### ISSUE TITLE
build.sbt file missing

### ISSUE THREAD

**Issue by ilanbiala** [pvillega/play2demo-jasmine#1]
The build.sbt file is missing. Can you add it in?

**Comment by pvillega** [comment]
Is missing because this is for an older version of Play. I'm not sure I'll
have time to edit this to upgrade it to Play 2.4, sorry about that

**Comment by ilanbiala** [comment]
@pvillega I think it's because you have SBT 0.11 and I'm using 0.13. Have you managed to run a successful AngularJS Jasmine test with Play 2.3?

**Comment by pvillega** [comment]
I missed the answer, and now it's a bit too late sorry 😅
